name: file_management
version: 6.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-95.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  
  shared_preferences: ^2.0.13
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

